---
spec/spec_helper_acceptance.rb:
  unmanaged: false

.puppet-lint.rc:
  enabled_lint_checks:
    - parameter_documentation
    - parameter_types

.github/workflows/ci.yml:
  with:
    unit_runs_on: 'cern-self-hosted'
